Repository lude-dev/niche-android, pull requests merged in 2021-06, with the labels that each got.

#33 fix: make only slide_panel_handle can be dragged
  app/src/main/res/drawable/background_slide_panel_round.xml
  app/src/main/res/drawable/ic_slide_panel_handle.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_slide.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: Fix

#39 fix: set status bar text color to black
  app/src/main/res/values/themes.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: Fix

#40 feat: make home slide fragment recycler view
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/implude/niche/presentation/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home_slide.xml
  app/src/main/res/layout/row_recycler_item.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: Fix, Type: New feature, Type: Refactor

#42 fix: make the map do not move when the panel is up
  app/src/main/res/layout/fragment_home_slide.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: Fix

#43 refactor: flatten constraint layout
  app/src/main/res/layout/fragment_home_slide.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: Refactor

#46 feat: make scroll view in fragment_home_slide.xml
  app/src/main/res/layout/fragment_home_slide.xml
Labels: Scope: Presentation

#47 chore(repo): specify mappers type
  app/src/main/java/com/implude/niche/data/repositories/PlaceRepositoryImpl.kt
  app/src/main/java/com/implude/niche/data/repositories/UserRepositoryImpl.kt
Labels: Scope: Data, Status: Waiting for reviews, Type: Fix

#49 feat: make participation fragment layout
  app/src/main/res/layout/fragment_participation.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#51 feat: create need fix report adapter item
  app/src/main/res/drawable-v24/dummy_store2.png
  app/src/main/res/drawable/dummy_store2.png
  app/src/main/res/drawable/ic_coin.xml
  app/src/main/res/layout/item_place_need_fix_report.xml
  app/src/main/res/values/colors.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#53 refactor: move MainActivity-related files to .presentation.main
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/implude/niche/presentation/home/HomeViewModel.kt
  app/src/main/java/com/implude/niche/presentation/main/MainActivity.kt
  app/src/main/java/com/implude/niche/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/implude/niche/presentation/main/home/HomeViewModel.kt
  app/src/main/java/com/implude/niche/presentation/main/home/PlaceAdapter.kt
  app/src/main/java/com/implude/niche/presentation/main/participation/ParticipationFragment.kt
  app/src/main/java/com/implude/niche/presentation/main/participation/ParticipationViewModel.kt
  app/src/main/java/com/implude/niche/presentation/main/user/UserFragment.kt
  app/src/main/java/com/implude/niche/presentation/main/user/UserViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_participation.xml
  app/src/main/res/layout/fragment_user.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: Refactor

#54 feat: implement presentation level data injection
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/implude/niche/presentation/NicheApplication.kt
  app/src/main/java/com/implude/niche/presentation/di/AppModule.kt
  app/src/main/java/com/implude/niche/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/implude/niche/presentation/main/participation/ParticipationFragment.kt
  app/src/main/java/com/implude/niche/presentation/main/user/UserFragment.kt
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#55 feat(vm): implement HomeViewModel
  app/src/main/java/com/implude/niche/data/LocalDataStore.kt
  app/src/main/java/com/implude/niche/presentation/di/AppModule.kt
  app/src/main/java/com/implude/niche/presentation/main/home/HomeViewModel.kt
  app/src/main/java/com/implude/niche/presentation/util/SingleLiveEvent.kt
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#56 feat(vm): implement ParticipationViewModel
  app/src/main/java/com/implude/niche/presentation/di/AppModule.kt
  app/src/main/java/com/implude/niche/presentation/main/participation/ParticipationViewModel.kt
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#57 feat: add participation fragment recyclerview and clean adapter
  .idea/misc.xml
  app/src/main/java/com/implude/niche/domain/models/ReducedPlaceModel.kt
  app/src/main/java/com/implude/niche/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/implude/niche/presentation/main/home/RowPlaceAdapter.kt
  app/src/main/java/com/implude/niche/presentation/main/participation/NeedFixPlaceAdapter.kt
  app/src/main/java/com/implude/niche/presentation/main/participation/ParticipationFragment.kt
  app/src/main/res/layout/fragment_participation.xml
  app/src/main/res/layout/item_place_need_fix_report.xml
  app/src/main/res/layout/row_recycler_item.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: Fix, Type: New feature, Type: Refactor

#58 feat(res): add place preview layout
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/layout/activity_place_preview.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#59 feat: add user tab layout elements
  app/src/main/res/drawable-v24/wallet_gray_box.xml
  app/src/main/res/drawable/ic_history.xml
  app/src/main/res/drawable/ic_wallet.xml
  app/src/main/res/layout/fragment_user.xml
  app/src/main/res/values/colors.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#60 feat(presentation): link ReducedPlaceModel data with ViewModel
  app/src/main/graphql/com/implude/niche/Place.graphql
  app/src/main/java/com/implude/niche/data/di/NetworkModule.kt
  app/src/main/java/com/implude/niche/data/mappers/NearPlacesMapper.kt
  app/src/main/java/com/implude/niche/data/repositories/LocalRepositoryImpl.kt
  app/src/main/java/com/implude/niche/domain/models/LocationModel.kt
  app/src/main/java/com/implude/niche/presentation/di/AppModule.kt
  app/src/main/java/com/implude/niche/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/implude/niche/presentation/main/home/HomeViewModel.kt
  app/src/main/java/com/implude/niche/presentation/main/home/RowPlaceAdapter.kt
  app/src/main/res/drawable/ic_marker_hearted.xml
  app/src/main/res/drawable/ic_marker_normal.xml
  app/src/main/res/layout/row_recycler_item.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#61 UI/create store detail activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/implude/niche/presentation/StoreDetailActivity.kt
  app/src/main/res/drawable-v24/comment_gray_box.xml
  app/src/main/res/drawable-v24/dummy_picture.png
  app/src/main/res/drawable-v24/dummy_picture2.png
  app/src/main/res/drawable/dummy_picture.png
  app/src/main/res/drawable/dummy_picture2.png
  app/src/main/res/drawable/ic_add_comment.xml
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/layout/activity_store_detail.xml
  app/src/main/res/values/colors.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#64 Mola
  app/src/main/res/layout/activity_store_detail.xml
  app/src/main/res/layout/fragment_participation.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#62 feat: create menu recycler item
  app/src/main/res/layout/menu_recycler_item.xml
Labels: Scope: Presentation, Type: New feature

#65 UI/create menu recycler item
  app/src/main/java/com/implude/niche/domain/models/CommentModel.kt
  app/src/main/res/layout/comment_recycler_item.xml
Labels: Scope: Presentation, Scope: Repository, Status: Waiting for reviews, Type: New feature

#66 fix: fix build issue of e7886c7 commit
  app/src/main/java/com/implude/niche/domain/models/CommentModel.kt
Labels: Scope: Repository, Status: Waiting for reviews, Type: Fix

#67 feat(presentation): add tag flexbox layout
  app/build.gradle
  app/src/main/graphql/com/implude/niche/Place.graphql
  app/src/main/java/com/implude/niche/data/repositories/PlaceRepositoryImpl.kt
  app/src/main/java/com/implude/niche/domain/repositories/PlaceRepository.kt
  app/src/main/java/com/implude/niche/presentation/StoreDetailActivity.kt
  app/src/main/java/com/implude/niche/presentation/StoreDetailViewModel.kt
  app/src/main/java/com/implude/niche/presentation/di/AppModule.kt
  app/src/main/java/com/implude/niche/presentation/main/home/HomeViewModel.kt
  app/src/main/res/drawable/tag_border.xml
  app/src/main/res/drawable/tag_divider.xml
  app/src/main/res/layout/activity_store_detail.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#68 feat(presentation): bind data to store detail activity
  app/src/main/java/com/implude/niche/data/mappers/NearFixReportsMapper.kt
  app/src/main/java/com/implude/niche/presentation/StoreDetailActivity.kt
  app/src/main/java/com/implude/niche/presentation/main/home/RowPlaceAdapter.kt
  app/src/main/res/layout/activity_store_detail.xml
  app/src/main/res/values/strings.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#69 chore(presentation): adjust initial slide panel height
  app/src/main/res/layout/fragment_home.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: Enhancement

#71 fix: add activity_store_detail.xml header layout
  app/src/main/res/layout/activity_store_detail.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: Fix

#70 feat: create edit store info activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/implude/niche/presentation/EditStoreInfoActivity.kt
  app/src/main/res/layout/activity_edit_store_info.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#72 feat: create certificate activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/implude/niche/presentation/CertificateActivity.kt
  app/src/main/res/drawable/button_disable.xml
  app/src/main/res/drawable/button_enable.xml
  app/src/main/res/drawable/for_elevation_box.xml
  app/src/main/res/layout/activity_certificate.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#74 feat: add comments and hearts more activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/implude/niche/presentation/main/user/MyCommentsActivity.kt
  app/src/main/java/com/implude/niche/presentation/main/user/MyHeartsActivity.kt
  app/src/main/res/layout/activity_my_comments.xml
  app/src/main/res/layout/activity_my_hearts.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature

#73 Fix edit store info and Add start activity
  app/src/main/java/com/implude/niche/presentation/EditStoreInfoActivity.kt
  app/src/main/java/com/implude/niche/presentation/StoreDetailActivity.kt
  app/src/main/java/com/implude/niche/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/implude/niche/presentation/main/participation/ParticipationFragment.kt
  app/src/main/res/layout/activity_edit_store_info.xml
  app/src/main/res/layout/activity_store_detail.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: Fix, Type: New feature, Type: Refactor

#75 fix: change go_back_arrow size to 18dp
  app/src/main/res/layout/activity_certificate.xml
  app/src/main/res/layout/activity_edit_store_info.xml
  app/src/main/res/layout/activity_my_comments.xml
  app/src/main/res/layout/activity_my_hearts.xml
  app/src/main/res/layout/activity_store_detail.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: Fix

#76 refactor: remove tags, images and menus from store detail
  app/src/main/res/layout/activity_edit_store_info.xml
Labels: Scope: Presentation, Status: Waiting for reviews, Type: New feature
